# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: vik_invites_development

test:
  <<: *default
  database: vik_invites_test

production:
  <<: *default
  database: vik_invites_production
  username: invite_manager
  password: <%= ENV["INVITE_MANAGER_DATABASE_PASSWORD"] %>
