# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: invite_manager_development

test:
  <<: *default
  database: invite_manager_test

production:
  <<: *default
  database: invite_manager_production
  username: invite_manager
  password: <%= ENV["INVITE_MANAGER_DATABASE_PASSWORD"] %>
